#include "boot_sound.h"

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include <rg_audio.h>
#include <rg_system.h>

// Symbols generated by target_add_binary_data() from assets/boot_c3.pcm.
extern const uint8_t boot_c3_pcm_start[] asm("_binary_assets_boot_c3_pcm_start");
extern const uint8_t boot_c3_pcm_end[] asm("_binary_assets_boot_c3_pcm_end");

#define BOOT_SOUND_FRAMES_PER_CHUNK 256

static void boot_sound_task(void *arg)
{
    (void)arg;

    const uint8_t *cursor = boot_c3_pcm_start;
    const size_t sample_count = (size_t)(boot_c3_pcm_end - boot_c3_pcm_start) / sizeof(int16_t);
    rg_audio_frame_t frames[BOOT_SOUND_FRAMES_PER_CHUNK];
    size_t sample_index = 0;

    while (sample_index < sample_count)
    {
        const size_t count = RG_MIN(BOOT_SOUND_FRAMES_PER_CHUNK, sample_count - sample_index);

        for (size_t i = 0; i < count; ++i)
        {
            int16_t sample;
            memcpy(&sample, cursor + ((sample_index + i) * sizeof(sample)), sizeof(sample));
            frames[i].left = sample;
            frames[i].right = sample;
        }

        rg_audio_submit(frames, count);
        sample_index += count;
    }
}

void boot_sound_play_c3(void)
{
    if (!rg_task_create("boot_sound", &boot_sound_task, NULL, 3 * 1024, 1, RG_TASK_PRIORITY_2, -1))
        RG_LOGE("Could not start Hands on Lab boot sound\n");
}
